version: "3"

services:
  node:
    image: node:15.8.0
    user: node
    ports:
      - 6000:3000
    env_file:
      - .env
    volumes:
      - .:/home/node
    entrypoint: yarn
    working_dir: /home/node
